### ISSUE TITLE
Grml 2018.12 / 2018.12-rc1 release checklist 

### ISSUE THREAD

**Issue by mika** [grml/grml#111]
### Coordinating remaining release work here

Issues + PRs:

- [ ] Go through [unmerged pull-requests](https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Agrml) and ensure everything release-relevant is merged
- [ ] Go through [project list](https://github.com/orgs/grml/projects/2) + ensure there are no release stoppers

Unresolved issues, not strictly release-stoppers though:

- [ ] Failed unmounting /lib/live/mount/medium (https://github.com/grml/grml/issues/109)

Documentation related:

- [ ] update FAQ for current release (https://github.com/grml/grml/issues/22)
- [ ] provide release notes
- [ ] update website

Verify and document networking behavior (default Grml boot vs. boot option `debian_networking`):

- [ ] ip=…
- [ ] ip=frommedia
- [ ] dns=…
- [ ] ethdevice=…

Issues to keep an eye on:

- [ ] unicode issues (https://github.com/grml/grml/issues/50)

Release check-list:

- [ ] ensure that `/etc/grml/fai/config/package_config/IGNORE` is empty!
- [ ] get rid of old(er) rc/stable release from Jenkins release jobs listed at https://jenkins.grml.org/view/Grml%20Release/ to have enough disk space available
- [ ] check for outdated packages in grml-live repos
```
reprepro -b /home/archive/grml-repo/archive listmatched grml-live '*'
```
- [ ] execute `~/bin/repodiff.pl | grep -ve linux-headers -ve linux-image -ve linux |  grep -v same` to check for differences between i386 and amd64 repos
- [ ] packages.grml.org -> check for pending uploads
- [ ] http://jenkins.grml.org/view/Grml%20Release/
  - [ ] adjust release name, version number + dpkg.list URL in *_Release jobs
  - [ ] build the *testing jobs and mark latest successful build as "Keep forever"
  - [ ] enable "Do not update chroot" option in *_Release jobs (see [ruby-runtime bug in Jenkins](https://issues.jenkins-ci.org/browse/JENKINS-18838))

Upload ISOs:

- [ ] archive previous release(s) at http://archive.grml.org/
- [ ] sign resulting *.sha1 files
- [ ] remove $current-release-2 (2nd previous release) files from /var/www/ftp-master.grml.org
- [ ] upload to `/var/www/ftp-master.grml.org` on download.grml.org (web-VM), check:
```
for f in *.sha1 ; sha1sum -c $f
for f in *.md5 ; md5sum -c $f
for f in *.sha1.asc ; sha1sum -c $f
```
- [ ] torrent files:
```
cd /home/tracker/torrents ; rm $OLD_RELEASE # (dead symlinks)
for f in /var/www/ftp-master.grml.org/*2018.12.iso ; /usr/local/bin/make_torrent $f
/etc/init.d/transmission-daemon restart
supervisorctl stop all; supervisorctl start all; /etc/init.d/supervisor status
```
- [ ] update index files (`~www/ftp-master.grml.org # vi index.*html`)
- [ ] update grml.org.git
```
/download/
/faq/ (release name)
/screenshots/
release notes
package information files
cd grml.org.git/files ; for f in *2018.12* ; ln -sf $f ${f%_*}_latest
https://grml.org/bugs/known/
```
- [ ] announce:
  - [ ] ml
  - [ ] twitter
  - [ ] blog.grml.org

Post-Release:

- [ ] review + rework Grml infrastructure

**Comment by schierlm** [comment]
About Unicode regressions: 
Regression in `2018.12-rc1` from `2017.05`: Commands that use line drawing characters (e.g. `pstree`) only work on tty1, not on the other ttys, regardless whether screen is active or not. Workaround `unicode-start </dev/tty2 >/dev/tty2` to make it work on tty2.

**Comment by jkirk** [comment]
Thank you @schierlm for your feedback. I just re-opened grml/grml-autoconfig#9. If you want to follow our updates on that issue, we will handle that issue over there...
