### ISSUE TITLE
Grml 2018.12 release checklist 

### ISSUE THREAD

**Issue by mika** [grml/grml#117]
### Coordinating remaining release work here

Issues + PRs:

- [x] Go through [unmerged pull-requests](https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Agrml) and ensure everything release-relevant is merged
- [x] Go through [project list](https://github.com/orgs/grml/projects/2) + ensure there are no release stoppers

Testing:

- [ ] Go through test roadmap (currently living on google docs)

Unresolved issues, not strictly release-stoppers though:

- [ ] Failed unmounting /lib/live/mount/medium (https://github.com/grml/grml/issues/109)

Documentation related:

- [x] update FAQ for current release (https://github.com/grml/grml/issues/22)
- [x] provide release notes
- [x] update website

Release check-list:

- [x] packages.grml.org -> check for pending uploads
- [x] ensure that `/etc/grml/fai/config/package_config/IGNORE` is empty!
- [x] get rid of old(er) rc/stable release from Jenkins release jobs listed at https://jenkins.grml.org/view/Grml%20Release/ to have enough disk space available
- [x] check for outdated packages in grml-live repos
```
reprepro -b /home/archive/grml-repo/archive listmatched grml-live '*'
```
- [x] execute `~/bin/repodiff.pl | grep -ve linux-headers -ve linux-image -ve linux |  grep -v same` to check for differences between i386 and amd64 repos
- [x] create copy of current grml-stable Debian repository as grml-$OLD_RELEASE-updates (doesn't apply to stable release process)
```
reprepro copyfilter grml-2017.05-updates grml-stable 'Architecture'
```
- [x] clear grml-stable Debian repository and copy grml-testing content to it (PS: we should cleanup linux stuff and other deprecated stuff from grml-testing once!)
```
reprepro removematched grml-stable '*'
reprepro copyfilter grml-stable grml-testing 'Architecture'
```
- [x] http://jenkins.grml.org/view/Grml%20Release/
  - [x] adjust release name, version number + dpkg.list URL in *_Release jobs
  - [x] build the *testing jobs and mark latest successful build as "Keep forever"
  - [x] enable "Do not update chroot" option in *_Release jobs (see [ruby-runtime bug in Jenkins](https://issues.jenkins-ci.org/browse/JENKINS-18838))

Upload ISOs:

- [x] archive previous release(s) at http://archive.grml.org/
- [x] sign resulting *.sha1 files
```
for f in *.sha1 ; gpg --clearsign $f
for f in *.iso ; gpg --output ${f}.asc --armor --detach-sig ${f}
```
- [x] remove $current-release-2 (2nd previous release) files from /var/www/ftp-master.grml.org
- [x] upload to `/var/www/ftp-master.grml.org` on download.grml.org (web-VM), check:
```
for f in *.sha1 ; sha1sum -c $f
for f in *.md5 ; md5sum -c $f
for f in *.sha1.asc ; sha1sum -c $f
```
- [x] torrent files:
```
cd /home/tracker/torrents ; rm $OLD_RELEASE # (dead symlinks)
for f in /var/www/ftp-master.grml.org/*2018.12.iso ; /usr/local/bin/make_torrent $f
/etc/init.d/transmission-daemon restart
supervisorctl stop all; supervisorctl start all; /etc/init.d/supervisor status
```
- [x] update index files (`~www/ftp-master.grml.org # vi index.*html`)
- [x] update grml.org.git
```
/download/
/faq/ (release name)
/screenshots/
release notes
package information files
cd grml.org.git/files ; for f in *2018.12* ; ln -sf $f ${f%_*}_latest
https://grml.org/bugs/known/
```
- [x] announce:
  - [x] ml
  - [x] twitter
  - [x] blog.grml.org
  - [x] IRC

**Comment by mika** [comment]
Done :) \o/
